spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mc_market
    username: postgres
    password: asror7887
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml


sentry:
  enabled: true
  dsn: https://73222d800d77b340faa1b9b005530fd0@o4508493706493952.ingest.de.sentry.io/4508493970341968
  environment: "dev"
  debug: false
  traces-sample-rate: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui
    groups-order: asc
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: "none"
  api-docs:
    path: /v3/docs

